### ISSUE TITLE
about raw gnss measurement

### ISSUE THREAD

**Issue by heiwa0519** [3DOM-FBK/Collaborative_Navigation#1]
Thank you and your team for this excellent work! In this dataset, the gnss information is position format, could you provide gnss information in raw data format, such as rinex or rtcm3, in order to research high-precision GNSS algorithms. Thank you very much.

**Comment by lcmrl** [comment]
Hi, sorry for the delay, we have only just managed to upload the raw GNSS data. Please let us know if anything is missing or there are problems with accessing the data.
